id: bitlang.cobol
version: 4.5.6
type: VS Code extension
name: COBOL
title: COBOL JCL PL I and DIR syntax support
description: COBOL JCL PL I and DIR syntax support
icon: https://bitlang.gallerycdn.vsassets.io/extensions/bitlang/cobol/4.5.6/1553819958949/Microsoft.VisualStudio.Services.Icons.Default
attributes:
  extension: "vscode:extension/bitlang.cobol"
  containerImage: "eclipse/che-theia-endpoint-runtime:next"