id: vscode.bitlang.cobol
version: 4.5.6
type: VS Code extension
name: COBOL
title: COBOL, JCL, PL/I & DIR syntax support
description: COBOL, JCL, PL/I & DIR syntax support
icon: https://bitlang.gallerycdn.vsassets.io/extensions/bitlang/cobol/4.5.6/1553819958949/Microsoft.VisualStudio.Services.Icons.Default
publisher: bitlang
repository: https://github.com/spgennard/vscode_cobol
category: Language
firstPublicationDate: "2019-03-29"
attributes:
  extension: "vscode:extension/bitlang.cobol"
  containerImage: "eclipse/che-theia-endpoint-runtime:next"