id: nickdodd79.gulptasks
version: 1.3.1
type: VS Code extension
name: Gulp Tasks
title: Gulp Tasks
description: Allows you to visualize and execute gulp tasks found in your workspaces.
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
attributes:
  extension: "vscode:extension/nickdodd79.gulptasks"